# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.FileField(null=True, upload_to='users')),
                ('numero', models.CharField(max_length=10)),
                ('Calle', models.CharField(max_length=60)),
                ('Colonia', models.CharField(max_length=60)),
                ('Municipio', models.CharField(max_length=20)),
                ('Estado', models.CharField(max_length=20)),
                ('Ciudad', models.CharField(max_length=20)),
                ('Pais', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
    ]
